name: Firebase App Distribution

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-and-distribute:
    name: Build and Distribute App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        run: npm install -g eas-cli

      - name: Login to Expo
        run: expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Build Android app
        run: eas build --platform android --profile preview --non-interactive

      - name: Build iOS app
        run: eas build --platform ios --profile preview --non-interactive

      - name: Download Android build
        run: |
          BUILD_ID=$(eas build:list --platform android --status finished --non-interactive --json | jq -r '.[0].id')
          eas build:download --id $BUILD_ID --output ./app-release.apk

      - name: Download iOS build
        run: |
          BUILD_ID=$(eas build:list --platform ios --status finished --non-interactive --json | jq -r '.[0].id')
          eas build:download --id $BUILD_ID --output ./app-release.ipa

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute Android app to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ./app-release.apk \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups "testers" \
            --release-notes "Build from GitHub Actions" \
            --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Distribute iOS app to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ./app-release.ipa \
            --app ${{ secrets.FIREBASE_IOS_APP_ID }} \
            --groups "testers" \
            --release-notes "Build from GitHub Actions" \
            --token "${{ secrets.FIREBASE_TOKEN }}"
